// Set the correct alphabetical order for the current language.
var languages =
[
	["af", "Afrikaans - af"],
	["sq", "Albanais - sq"],
	["de", "Allemand - de"],
	["am", "Amharique - am"],
	["en", "Anglais - en"],
	["st", "Anglais Du Sud - st"],
	["ar", "Arabe - ar"],
	["hy", "Arménien - hy"],
	["as", "Assamais - as"],
	["ay", "Aymara - ay"],
	["az", "Azerbaïdjan - az"],
	["eu", "Basque - eu"],
	["bn", "Bengali - bn"],
	["bh", "Bhojpuri - bh"],
	["be", "Biélorusse - be"],
	["my", "Birmanie (Birman) - my"],
	["bs", "Bosniaque - bs"],
	["bg", "Bulgare - bg"],
	["ca", "Catalan - ca"],
	["ceb", "Cebuano - ceb"],
	["ny", "Chichewa - ny"],
	["zh", "Chinois - zh"],
	["zh-CN", "Chinois (Simplifié) - zh-CN"],
	["zh-TW", "Chinois (Traditionnel) - zh-TW"],
	["si", "Cinghalais - si"],
	["ko", "Coréen - ko"],
	["co", "Corse - co"],
	["ht", "Créole Haïtien - ht"],
	["hr", "Croate - hr"],
	["da", "Danois - da"],
	["dv", "Dhivehi - dv"],
	["es", "Espagnol - es"],
	["eo", "Espéranto - eo"],
	["et", "Estonien - et"],
	["ee", "Éwé - ee"],
	["fa", "Farsi / Persan - fa"],
	["fi", "Finlandais - fi"],
	["fr", "Français - fr"],
	["fy", "Frison (Occidental) - fy"],
	["gd", "Gaélique (Écossais) - gd"],
	["gl", "Galicien - gl"],
	["cy", "Gallois - cy"],
	["ka", "Géorgien - ka"],
	["el", "Grec - el"],
	["gn", "Guarani - gn"],
	["gu", "Gujarati - gu"],
	["ha", "Haoussa - ha"],
	["haw", "Hawaïen - haw"],
	["iw", "Hébreu - iw"],
	["hi", "Hindi - hi"],
	["hmn", "Hmong - hmn"],
	["hu", "Hongrois - hu"],
	["ig", "Ibo - ig"],
	["id", "Indonésien - id"],
	["ga", "Irlandais - ga"],
	["is", "Islandais - is"],
	["it", "Italien - it"],
	["ja", "Japonais - ja"],
	["jw", "Javanais - jw"],
	["kn", "Kannada - kn"],
	["kk", "Kazakhstan - kk"],
	["km", "Khmer - km"],
	["rw", "Kinyarwanda - rw"],
	["ky", "Kirghize - ky"],
	["kri", "Krio - kri"],
	["ku", "Kurde - ku"],
	["lo", "Laotien - lo"],
	["la", "Latin - la"],
	["lv", "Letton - lv"],
	["ln", "Lingala - ln"],
	["lt", "Lituanien - lt"],
	["lg", "Luganda - lg"],
	["lb", "Luxembourgeois - lb"],
	["mk", "Macédonien - mk"],
	["ms", "Malais - ms"],
	["ml", "Malayalam - ml"],
	["mg", "Malgache - mg"],
	["mt", "Maltais - mt"],
	["mi", "Maori - mi"],
	["mr", "Marathe - mr"],
	["mn", "Mongol - mn"],
	["nl", "Néerlandais - nl"],
	["ne", "Népalais - ne"],
	["no", "Norvégien - no"],
	["or", "Oriya - or"],
	["om", "Oromo - om"],
	["ug", "Ouïghour - ug"],
	["ur", "Ourdou - ur"],
	["uz", "Ouzbek - uz"],
	["ps", "Pachtou - ps"],
	["pa", "Pendjabi - pa"],
	["pl", "Polonais - pl"],
	["pt", "Portugais - pt"],
	["qu", "Quechua - qu"],
	["cs", "République Tchèque - cs"],
	["ro", "Roumain - ro"],
	["ru", "Russe - ru"],
	["sm", "Samoa - sm"],
	["sa", "Sanskrit - sa"],
	["nso", "Sepedi - nso"],
	["sr", "Serbe - sr"],
	["sn", "Shona - sn"],
	["sd", "Sindhi - sd"],
	["sk", "Slovaquie - sk"],
	["sl", "Slovène - sl"],
	["so", "Somalie - so"],
	["sv", "Suédois - sv"],
	["su", "Sundanais - su"],
	["sw", "Swahili - sw"],
	["tg", "Tadjik - tg"],
	["tl", "Tagalog / Philippin - tl"],
	["ta", "Tamil - ta"],
	["tt", "Tatar - tt"],
	["te", "Télougou - te"],
	["th", "Thaïlandais - th"],
	["ti", "Tigrinya - ti"],
	["ts", "Tsonga - ts"],
	["tr", "Turc - tr"],
	["tk", "Turkmène - tk"],
	["ak", "Twi - ak"],
	["uk", "Ukrainien - uk"],
	["vi", "Vietnamien - vi"],
	["xh", "Xhosa - xh"],
	["yi", "Yiddish - yi"],
	["yo", "Yoruba - yo"],
	["zu", "Zoulou - zu"]
];

exports.languages = languages;
