// Set the correct alphabetical order for the current language.
var languages =
[
	["af", "Africaans - af"],
	["sq", "Albanés - sq"],
	["de", "Alemán - de"],
	["am", "Amárico - am"],
	["ar", "Arábica - ar"],
	["hy", "Armenio - hy"],
	["as", "Assamese - as"],
	["ay", "Aymara - ay"],
	["az", "Azerbaiyán - az"],
	["bn", "Bengalí - bn"],
	["bh", "Bhojpuri - bh"],
	["be", "Bielorruso - be"],
	["bs", "Bosnio - bs"],
	["bg", "Búlgaro - bg"],
	["kn", "Canadá - kn"],
	["ca", "Catalán - ca"],
	["ceb", "Cebuano - ceb"],
	["ny", "Chichewa - ny"],
	["zh", "Chino - zh"],
	["zh-CN", "Chino (Simplificado) - zh-CN"],
	["zh-TW", "Chino (Tradicional) - zh-TW"],
	["si", "Cingalés - si"],
	["ko", "Coreano - ko"],
	["co", "Corso - co"],
	["ht", "Criollo Haitiano - ht"],
	["hr", "Croata - hr"],
	["da", "Danés - da"],
	["dv", "Dhivehi - dv"],
	["sk", "Eslovaquia - sk"],
	["sl", "Esloveno - sl"],
	["es", "Español - es"],
	["eo", "Esperanto - eo"],
	["et", "Estonio - et"],
	["ee", "Ewe - ee"],
	["fa", "Farsi / Persa - fa"],
	["fi", "Finlandés - fi"],
	["fr", "Francés - fr"],
	["fy", "Frisón (Occidental) - fy"],
	["gd", "Gaélico (Escocés) - gd"],
	["cy", "Galés - cy"],
	["gl", "Gallego - gl"],
	["ka", "Georgiano - ka"],
	["el", "Griego - el"],
	["gn", "Guaraní - gn"],
	["gu", "Guyaratí - gu"],
	["ha", "Hausa - ha"],
	["haw", "Hawaiano - haw"],
	["iw", "Hebreo - iw"],
	["hi", "Hindi - hi"],
	["hmn", "Hmong - hmn"],
	["nl", "Holandés - nl"],
	["hu", "Húngaro - hu"],
	["ig", "Igbo - ig"],
	["id", "Indonesio - id"],
	["en", "Inglés - en"],
	["st", "Inglés Del Sur - st"],
	["ga", "Irlandesa - ga"],
	["is", "Islandés - is"],
	["it", "Italiano - it"],
	["ja", "Japonés - ja"],
	["jw", "Javanés - jw"],
	["km", "Jemer - km"],
	["kk", "Kazajstán - kk"],
	["rw", "Kinyarwanda - rw"],
	["ky", "Kirguís - ky"],
	["kri", "Krio - kri"],
	["ku", "Kurdo - ku"],
	["lo", "Laosiano - lo"],
	["la", "Latín - la"],
	["lv", "Letón - lv"],
	["ln", "Lingala - ln"],
	["lt", "Lituano - lt"],
	["lg", "Luganda - lg"],
	["lb", "Luxemburgués - lb"],
	["mk", "Macedónio - mk"],
	["mg", "Madagascarí - mg"],
	["ml", "Malayalam - ml"],
	["ms", "Malayo - ms"],
	["mt", "Maltés - mt"],
	["mi", "Maorí - mi"],
	["mr", "Marathi - mr"],
	["mn", "Mongol - mn"],
	["my", "Myanmar (Birmano) - my"],
	["ne", "Nepalí - ne"],
	["no", "Noruego - no"],
	["or", "Oriya - or"],
	["om", "Oromo - om"],
	["ps", "Pastún - ps"],
	["pl", "Polaco - pl"],
	["pt", "Portugués - pt"],
	["pa", "Punjabi - pa"],
	["qu", "Quechua - qu"],
	["cs", "República Checa - cs"],
	["ro", "Rumano - ro"],
	["ru", "Ruso - ru"],
	["sm", "Samoano - sm"],
	["sa", "Sanskrit - sa"],
	["nso", "Sepedi - nso"],
	["sr", "Serbio - sr"],
	["sn", "Shona - sn"],
	["sd", "Sindhi - sd"],
	["so", "Somalia - so"],
	["sv", "Sueco - sv"],
	["su", "Sundanés - su"],
	["sw", "Swahili - sw"],
	["tl", "Tagalo / Filipino - tl"],
	["th", "Tailandés - th"],
	["ta", "Tamil - ta"],
	["tt", "Tártaro - tt"],
	["tg", "Tayiko - tg"],
	["te", "Telugu - te"],
	["ti", "Tigrinya - ti"],
	["ts", "Tsonga - ts"],
	["tr", "Turco - tr"],
	["tk", "Turkmeno - tk"],
	["ak", "Twi - ak"],
	["uk", "Ucranio - uk"],
	["ug", "Uigur - ug"],
	["ur", "Urdu - ur"],
	["uz", "Uzbeco - uz"],
	["eu", "Vasco - eu"],
	["vi", "Vietnamita - vi"],
	["xh", "Xhosa - xh"],
	["yi", "Yídish - yi"],
	["yo", "Yoruba - yo"],
	["zu", "Zulú - zu"]
];

exports.languages = languages;
