// Set the correct alphabetical order for the current language.
var languages =
[
	["af", "Afrikaans - af"],
	["sq", "Albanian - sq"],
	["am", "Amharic - am"],
	["ar", "Arabic - ar"],
	["hy", "Armenian - hy"],
	["as", "Assamese - as"],
	["ay", "Aymara - ay"],
	["az", "Azerbaijani - az"],
	["eu", "Basque - eu"],
	["be", "Belarusian - be"],
	["bn", "Bengali - bn"],
	["bh", "Bhojpuri - bh"],
	["bs", "Bosnian - bs"],
	["bg", "Bulgarian - bg"],
	["ca", "Catalan - ca"],
	["ceb", "Cebuano - ceb"],
	["ny", "Chichewa - ny"],
	["zh", "Chinese - zh"],
	["zh-CN", "Chinese (Simplified) - zh-CN"],
	["zh-TW", "Chinese (Traditional) - zh-TW"],
	["co", "Corsican - co"],
	["hr", "Croatian - hr"],
	["cs", "Czech - cs"],
	["da", "Danish - da"],
	["dv", "Dhivehi - dv"],
	["nl", "Dutch - nl"],
	["en", "English - en"],
	["eo", "Esperanto - eo"],
	["et", "Estonian - et"],
	["ee", "Ewe - ee"],
	["fa", "Farsi / Persian - fa"],
	["fi", "Finnish - fi"],
	["fr", "French - fr"],
	["fy", "Frisian (Western) - fy"],
	["gd", "Gaelic (Scottish) - gd"],
	["gl", "Galician - gl"],
	["ka", "Georgian - ka"],
	["de", "German - de"],
	["el", "Greek - el"],
	["gn", "Guarani - gn"],
	["gu", "Gujarati - gu"],
	["ht", "Haitian Creole - ht"],
	["ha", "Hausa - ha"],
	["haw", "Hawaiian - haw"],
	["iw", "Hebrew - iw"],
	["hi", "Hindi - hi"],
	["hmn", "Hmong - hmn"],
	["hu", "Hungarian - hu"],
	["is", "Icelandic - is"],
	["ig", "Igbo - ig"],
	["id", "Indonesian - id"],
	["ga", "Irish - ga"],
	["it", "Italian - it"],
	["ja", "Japanese - ja"],
	["jw", "Javanese - jw"],
	["kn", "Kannada - kn"],
	["kk", "Kazakh - kk"],
	["km", "Khmer - km"],
	["rw", "Kinyarwanda - rw"],
	["ko", "Korean - ko"],
	["kri", "Krio - kri"],
	["ku", "Kurdish - ku"],
	["ky", "Kyrgyz - ky"],
	["lo", "Lao - lo"],
	["la", "Latin - la"],
	["lv", "Latvian - lv"],
	["ln", "Lingala - ln"],
	["lt", "Lithuanian - lt"],
	["lg", "Luganda - lg"],
	["lb", "Luxembourgish - lb"],
	["mk", "Macedonian - mk"],
	["mg", "Malagasy - mg"],
	["ms", "Malay - ms"],
	["ml", "Malayalam - ml"],
	["mt", "Maltese - mt"],
	["mi", "Maori - mi"],
	["mr", "Marathi - mr"],
	["mn", "Mongolian - mn"],
	["my", "Myanmar (Burmese) - my"],
	["ne", "Nepali - ne"],
	["no", "Norwegian - no"],
	["or", "Oriya - or"],
	["om", "Oromo - om"],
	["ps", "Pashto - ps"],
	["pl", "Polish - pl"],
	["pt", "Portuguese - pt"],
	["pa", "Punjabi - pa"],
	["qu", "Quechua - qu"],
	["ro", "Romanian - ro"],
	["ru", "Russian - ru"],
	["sm", "Samoan - sm"],
	["sa", "Sanskrit - sa"],
	["nso", "Sepedi - nso"],
	["sr", "Serbian - sr"],
	["sn", "Shona - sn"],
	["sd", "Sindhi - sd"],
	["si", "Sinhala - si"],
	["sk", "Slovak - sk"],
	["sl", "Slovenian - sl"],
	["so", "Somali - so"],
	["st", "Southern Sotho - st"],
	["es", "Spanish - es"],
	["su", "Sundanese - su"],
	["sw", "Swahili - sw"],
	["sv", "Swedish - sv"],
	["tl", "Tagalog / Filipino - tl"],
	["tg", "Tajik - tg"],
	["ta", "Tamil - ta"],
	["tt", "Tatar - tt"],
	["te", "Telugu - te"],
	["th", "Thai - th"],
	["ti", "Tigrinya - ti"],
	["ts", "Tsonga - ts"],
	["tr", "Turkish - tr"],
	["tk", "Turkmen - tk"],
	["ak", "Twi - ak"],
	["uk", "Ukrainian - uk"],
	["ur", "Urdu - ur"],
	["ug", "Uyghur - ug"],
	["uz", "Uzbek - uz"],
	["vi", "Vietnamese - vi"],
	["cy", "Welsh - cy"],
	["xh", "Xhosa - xh"],
	["yi", "Yiddish - yi"],
	["yo", "Yoruba - yo"],
	["zu", "Zulu - zu"]
];

exports.languages = languages;
